### ISSUE TITLE
add CP1252 Encoding

### ISSUE THREAD

**Issue by sboosali** [haskell/text#252]
i.e. add these to `Data.Text.Encoding`:

* `decodeCP1252With`
* `encodeCP1252With`

> Windows-1252 or CP-1252 (code page – 1252) is a single-byte character encoding of the Latin alphabet, used by default in the legacy components of Microsoft Windows in English and some other Western languages (other languages use different default encodings).
> It is probably the most-used 8-bit character encoding in the world.

from <https://en.wikipedia.org/wiki/Windows-1252>.

this encoding comes up under Windows development. For example, Dragon Naturally Speaking, a speech recognition engine, returns dictations in the "native, legacy" CP-1252 format.

also, this encoding is supported by the python standard library:

```
>>> u'café'.encode('cp1252')
'caf\xe9'
```

**Comment by sullyj3** [comment]
is there a workaround for this in the meantime?

**Comment by Lysxia** [comment]
I'm not sure. From a cursory search, there is the [encoding](https://hackage.haskell.org/package/encoding) library which handles CP1252, but uses `String` instead of `Text`.

I think the simplest outcome would be for someone to make a new package providing this encoding for `Text`.

I'm not sure what a good policy would be to decide whether to add support for an encoding within the text library. I'm leaning towards not adding any. I think we should keep the scope of the text library limited because (1) we don't have too much bandwidth to maintain it, (2) a practical upside to small packages is that they are easier to update for bug fixes and new features, with text being such a central library you are more likely to be blocked by an upper bound for unrelated reasons.

What downsides are there to having CP1252 support in a separate package?

**Comment by sullyj3** [comment]
I tracked down this package [text-icu](https://hackage.haskell.org/package/text-icu) which seems to do the trick

```haskell
import qualified Data.Text.ICU.Convert as ICUConvert

do
    converter <- ICUConvert.open "CP1252" Nothing
    let decodedText = ICUConvert.toUnicode converter byteStringToDecode
```

**Comment by Bodigrim** [comment]
> I'm leaning towards not adding any.

Same. Indeed, there is `text-icu` to work with non-standard encodings. I suggest to close.
