### ISSUE TITLE
`hGetLine` throws `EOF` exception 

### ISSUE THREAD

**Issue by nikivazou** [haskell/text#258]
At `text 1.2.3.1`, when I run 
```
openFile "emptyFile" ReadWriteMode >>= hGetLine
```
with emptyFile being an empty file, it throws ` hGetLine: end of file`. 
Shouldn't it just wait like `getLine`?

**Comment by hvr** [comment]
> Shouldn't it just wait like `getLine`?

For one the behaviour of `text` is consistent with  `base`'s `System.IO.{openFile,hGetLine}` which too would throw an EOF error for an empty file.

Also, `getLine` operates on stdin; and `getLine` only "waits" as long as the *thing* that `stdin` is connected to (usually your terminal) hasn't been closed from the other end of the channel. But if you invoked a program that invokes `getLine` as `MyProg < /dev/null` it also wouldn't wait and trigger an EOF exception.

**Comment by nikivazou** [comment]
Makes sense! Thanks a lot! 

So, to prevent the exception, I need to check `hIsEOF` before I call `hGetLine`?

**Comment by hvr** [comment]
@nikivazou essentially yes; the problem is that `hGetLine` has no other way to tell that it reached EOF as e.g. an empty string "" (like it'd be customary for Haskells `hGet`-ish operations to do on EOFs) could also mean that you have an empty line.

Alternatively (if your use-case permits this) you could read in all at once via `hGetContents` and apply `lines` on it; either strict or lazy `Text` depending on your input size.

**Comment by nikivazou** [comment]
Thanks!
