### ISSUE TITLE
Cut release for GHC 8.10.1

### ISSUE THREAD

**Issue by bgamari** [haskell/text#273]
GHC 8.10.1 will ship with `text` based upon 1127b30e1e0affa08f056e35ad17957b12982ba3. It would be great to have a release based upon this commit sometime in the next week.

**Comment by bgamari** [comment]
Ping.

**Comment by bgamari** [comment]
Whoops, didn't mean to close.

**Comment by bgamari** [comment]
@hvr, this is getting quite urgent.

**Comment by bgamari** [comment]
@hvr, I really need at least an acknowledgement, please.

If you think that the changes from 1.2.3.1 (two warnings fixes and removal of `fail` from the `Monad IParser` instance) do not warrant a release then that is absolutely fine. However, I do need to know one way or another and we need to start moving on making a release if one is needed.

**Comment by hvr** [comment]
(The discussion was moved to Email on Feb 14 and subsequently a text-1.2.3.2 release candidate was prepared and uploaded to Hackage; unfortunately I never got feedback on my last replies, so I made educated guesses based on the GHC 8.10.1 release and acted accordingly)

The candidate has been published as http://hackage.haskell.org/package/text-1.2.3.2 and a Git tag `v1.2.3.2` was pushed

The end-result is that

- GHC 8.6.3 ships with `text-1.2.3.1`
- GHC 8.8.[123] ship with `text-1.2.4.0`
- GHC 8.10.1 ships with `text-1.2.3.2`

The version downgrade in GHC 8.10.1 is intentional and was requested by GHC HQ to avoid delaying the GHC 8.10.1 release (even though ironically it still ended up being delayed anyway by over a month due to other blockers...)
