### ISSUE TITLE
spanWith, takeWhileWith

### ISSUE THREAD

**Issue by devvythelopper** [haskell/text#362]
It would be nice to have a variant of `span` and a variant of `takeWhile` that do not just apply a predicate, but also fold over a value.

The practical application I have in mind is to `span` or `takeWhile` but only up to a maximum number of characters. This of course could be implemented if there was a `spanMax` and `takeWhileMax` but a generalized `spanWith` and `takeWhileWith` that also do a fold (in this case over the number of characters already selected by the predicate) seems to be the better choice to me.

**Comment by lehmacdj** [comment]
`takeWhileMax n predicate = takeWhile predicate . take n` and should have fairly similar performance characteristics to the dedicated version due to fusion so at least for your practical application I think the current interface is fine. 

The more general version maybe still is necessary if you want to do something more complicated though; I don't see a way to cobble it together out of existing library functions in a good way.

**Comment by phadej** [comment]
@lehmacdj there is no fusion (#348)

**Comment by lehmacdj** [comment]
Good to know, sad to hear though, but the discussion in that linked issue makes sense

**Comment by Lysxia** [comment]
This is implemented in PR #437 (which was originally motivated by issue #178, which is the same issue as this).
