### ISSUE TITLE
Data.Text.replicate true complexity?

### ISSUE THREAD

**Issue by googleson78** [haskell/text#370]
The changelog claims that the complexity of `Data.Text.replicate` is `O(log(n))` since 1.2.4.0, however [the docs](https://hackage.haskell.org/package/text-1.2.5.0/docs/Data-Text.html#v:replicate) state that the complexity is `O(n*m)`.

Is one of these wrong, or am I misunderstanding?

**Comment by kuk0** [comment]
that's misleading; the change was that when making copies, we proceed by doubling ~log n times instead of copying n times
ultimately we call `memcpy` (or some fast primitive which copies a large block of data) log n times instead of n times which is faster, but the overall complexity is still O(n*m) CPU instructions

**Comment by Lysxia** [comment]
Clarified changelog in #434
