### ISSUE TITLE
Release text-2.1 [was: Release text-2.0.3?]

### ISSUE THREAD

**Issue by Bodigrim** [haskell/text#532]
I hoped us to be able to make a new release of `text-2.1.0` from `master`, but GHC team asked not to introduce breaking changes to GHC 9.8 at this stage. Given several important bug fixes recently, we should probably create a release branch for `text-2.0.3`, reverting breaking changes. If it sounds good, I can give it a go next week. @Lysxia what do you think?

**Comment by Lysxia** [comment]
Sounds good. I'll be available to review and help you with anything.

**Comment by TeofilC** [comment]
One thing to consider here is whether to include 2640dd620fae76deba7d0d75200a1ea258bd0ebe
I've noticed that this can break code that depends on `ByteArray` being a constructor of `Array`, see: https://gitlab.haskell.org/ghc/ghc/-/issues/23758

**Comment by Bodigrim** [comment]
My mood has changed: given ever changing nature of GHC release schedule, I don't feel like cherry-picking commits to release `text-2.0.3` is a good investment of my time this summer. Still happy to cut `text-2.1.0` from the `master` branch.

**Comment by bgamari** [comment]
@Bodigrim, I have noted the breakage from https://github.com/haskell/text/commit/2640dd620fae76deba7d0d75200a1ea258bd0ebe in the release notes in the hope that you will reconsider.

However, if we must ship 2.1.0 then it would be appreciated if you could cut the release soon so we can ship it with alpha 4, which is due to ship on 13 Sept 2023. Alpha 4 will be the last prerelease before the release candidate.

**Comment by Bodigrim** [comment]
Great, I'll prepare `text-2.1` for release from HEAD then.

**Comment by Lysxia** [comment]
text 2.1 is now out on Hackage. Let me know if you run into any issues.
